version: '3.1'

services:

  todo-mysql:
    image: mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - todo-data:/var/lib/mysql
      - ./db/set_up/create_schema_objects.sql:/docker-entrypoint-initdb.d/1.sql


volumes:
  todo-data: