// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package restapi

import (
	"time"
)

// CategoryOut Response type for category related services.
type CategoryOut struct {
	// Created Point in time when this category was created.
	Created time.Time `json:"created"`

	// Description Category description.
	Description *string `json:"description,omitempty"`

	// Id Id of category.
	Id int32 `json:"id"`

	// LastChanged Point in time when this category was last modified.
	LastChanged time.Time `json:"last_changed"`

	// Name Category name.
	Name string `json:"name"`
}

// CreateCategoryIn Request type for CreateCategory service.
type CreateCategoryIn struct {
	// Description Category description.
	Description *string `json:"description,omitempty"`

	// Name Category name.
	Name string `json:"name"`
}

// PostV1CategoryJSONRequestBody defines body for PostV1Category for application/json ContentType.
type PostV1CategoryJSONRequestBody = CreateCategoryIn
